source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'MoyaDemo' do

pod 'Moya', '~> 14.0'
pod 'Moya/RxSwift', '~> 14.0'
#pod 'Moya/ReactiveSwift', '~> 14.0'
#pod 'SwiftyJSON', '~> 4.0'
pod 'ProgressHUD'
end
